/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BluesNotehubJs);
  }
}(this, function(expect, BluesNotehubJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BluesNotehubJs.EnvironmentVariablesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EnvironmentVariablesApi', function() {
    describe('deleteDeviceEnvironmentVariable', function() {
      it('should call deleteDeviceEnvironmentVariable successfully', function(done) {
        //uncomment below and update the code to test deleteDeviceEnvironmentVariable
        //instance.deleteDeviceEnvironmentVariable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFleetEnvironmentVariable', function() {
      it('should call deleteFleetEnvironmentVariable successfully', function(done) {
        //uncomment below and update the code to test deleteFleetEnvironmentVariable
        //instance.deleteFleetEnvironmentVariable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProjectEnvironmentVariable', function() {
      it('should call deleteProjectEnvironmentVariable successfully', function(done) {
        //uncomment below and update the code to test deleteProjectEnvironmentVariable
        //instance.deleteProjectEnvironmentVariable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDeviceEnvironmentVariables', function() {
      it('should call getDeviceEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test getDeviceEnvironmentVariables
        //instance.getDeviceEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDeviceEnvironmentVariablesByPin', function() {
      it('should call getDeviceEnvironmentVariablesByPin successfully', function(done) {
        //uncomment below and update the code to test getDeviceEnvironmentVariablesByPin
        //instance.getDeviceEnvironmentVariablesByPin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFleetEnvironmentVariables', function() {
      it('should call getFleetEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test getFleetEnvironmentVariables
        //instance.getFleetEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectEnvironmentVariables', function() {
      it('should call getProjectEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test getProjectEnvironmentVariables
        //instance.getProjectEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putDeviceEnvironmentVariables', function() {
      it('should call putDeviceEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test putDeviceEnvironmentVariables
        //instance.putDeviceEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putDeviceEnvironmentVariablesByPin', function() {
      it('should call putDeviceEnvironmentVariablesByPin successfully', function(done) {
        //uncomment below and update the code to test putDeviceEnvironmentVariablesByPin
        //instance.putDeviceEnvironmentVariablesByPin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putFleetEnvironmentVariables', function() {
      it('should call putFleetEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test putFleetEnvironmentVariables
        //instance.putFleetEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putProjectEnvironmentVariables', function() {
      it('should call putProjectEnvironmentVariables successfully', function(done) {
        //uncomment below and update the code to test putProjectEnvironmentVariables
        //instance.putProjectEnvironmentVariables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
