/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NotehubJs);
  }
})(this, function (expect, NotehubJs) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new NotehubJs.Edgeimpulse();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("Edgeimpulse", function () {
    it("should create an instance of Edgeimpulse", function () {
      // uncomment below and update the code to test Edgeimpulse
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be.a(NotehubJs.Edgeimpulse);
    });

    it('should have the property fleets (base name: "fleets")', function () {
      // uncomment below and update the code to test the property fleets
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property filter (base name: "filter")', function () {
      // uncomment below and update the code to test the property filter
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property timeout (base name: "timeout")', function () {
      // uncomment below and update the code to test the property timeout
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property apiKey (base name: "api_key")', function () {
      // uncomment below and update the code to test the property apiKey
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function () {
      // uncomment below and update the code to test the property filename
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property deviceType (base name: "device_type")', function () {
      // uncomment below and update the code to test the property deviceType
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property intervalMs (base name: "interval_ms")', function () {
      // uncomment below and update the code to test the property intervalMs
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property deviceName (base name: "device_name")', function () {
      // uncomment below and update the code to test the property deviceName
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function () {
      // uncomment below and update the code to test the property label
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });

    it('should have the property sensors (base name: "sensors")', function () {
      // uncomment below and update the code to test the property sensors
      //var instance = new NotehubJs.Edgeimpulse();
      //expect(instance).to.be();
    });
  });
});
