/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NotehubJs);
  }
})(this, function (expect, NotehubJs) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new NotehubJs.GetBillingAccount200Response();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("GetBillingAccount200Response", function () {
    it("should create an instance of GetBillingAccount200Response", function () {
      // uncomment below and update the code to test GetBillingAccount200Response
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be.a(NotehubJs.GetBillingAccount200Response);
    });

    it('should have the property name (base name: "name")', function () {
      // uncomment below and update the code to test the property name
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function () {
      // uncomment below and update the code to test the property owner
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be();
    });

    it('should have the property plan (base name: "plan")', function () {
      // uncomment below and update the code to test the property plan
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be();
    });

    it('should have the property suspended (base name: "suspended")', function () {
      // uncomment below and update the code to test the property suspended
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be();
    });

    it('should have the property uid (base name: "uid")', function () {
      // uncomment below and update the code to test the property uid
      //var instance = new NotehubJs.GetBillingAccount200Response();
      //expect(instance).to.be();
    });
  });
});
