/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NotehubJs);
  }
})(this, function (expect, NotehubJs) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new NotehubJs.QuestionDataResponseLineChart();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("QuestionDataResponseLineChart", function () {
    it("should create an instance of QuestionDataResponseLineChart", function () {
      // uncomment below and update the code to test QuestionDataResponseLineChart
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be.a(NotehubJs.QuestionDataResponseLineChart);
    });

    it('should have the property type (base name: "type")', function () {
      // uncomment below and update the code to test the property type
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function () {
      // uncomment below and update the code to test the property title
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property property (base name: "property")', function () {
      // uncomment below and update the code to test the property property
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property displayValue (base name: "displayValue")', function () {
      // uncomment below and update the code to test the property displayValue
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property splitBy (base name: "splitBy")', function () {
      // uncomment below and update the code to test the property splitBy
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function () {
      // uncomment below and update the code to test the property startDate
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function () {
      // uncomment below and update the code to test the property endDate
      //var instance = new NotehubJs.QuestionDataResponseLineChart();
      //expect(instance).to.be();
    });
  });
});
