/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NotehubJs);
  }
})(this, function (expect, NotehubJs) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new NotehubJs.RouteLog();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("RouteLog", function () {
    it("should create an instance of RouteLog", function () {
      // uncomment below and update the code to test RouteLog
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be.a(NotehubJs.RouteLog);
    });

    it('should have the property date (base name: "date")', function () {
      // uncomment below and update the code to test the property date
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property routeUID (base name: "routeUID")', function () {
      // uncomment below and update the code to test the property routeUID
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property eventUID (base name: "eventUID")', function () {
      // uncomment below and update the code to test the property eventUID
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property attn (base name: "attn")', function () {
      // uncomment below and update the code to test the property attn
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function () {
      // uncomment below and update the code to test the property status
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function () {
      // uncomment below and update the code to test the property text
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function () {
      // uncomment below and update the code to test the property url
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function () {
      // uncomment below and update the code to test the property duration
      //var instance = new NotehubJs.RouteLog();
      //expect(instance).to.be();
    });
  });
});
