/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class AddDeviceToFleetsRequest {
  constructor(fleetUids: string[]);

  "fleet_uids": string[];

  static constructFromObject(
    data: any,
    obj?: AddDeviceToFleetsRequest,
  ): AddDeviceToFleetsRequest;
  static validateJSON(data: any): boolean;
}

export default AddDeviceToFleetsRequest;
