/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class AlertDataInner {
  constructor();

  "alert_source"?: "app" | "device";
  "source"?: string;
  "source_type"?: "event" | "device";
  "source_uid"?: string;
  "value"?: number;
  "when"?: string;

  static readonly AlertSourceEnum: { app: "app"; device: "device" };
  static readonly SourceTypeEnum: { event: "event"; device: "device" };

  static constructFromObject(data: any, obj?: AlertDataInner): AlertDataInner;
  static validateJSON(data: any): boolean;
}

export default AlertDataInner;
