/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The AnalyticsSessionsData model module.
 * @module model/AnalyticsSessionsData
 * @version 1.0.37
 */
class AnalyticsSessionsData {
  /**
   * Constructs a new <code>AnalyticsSessionsData</code>.
   * @alias module:model/AnalyticsSessionsData
   * @param period {Date}
   * @param sessions {Number}
   * @param uniqueDevices {Number}
   * @param totalBytes {Number}
   */
  constructor(period, sessions, uniqueDevices, totalBytes) {
    AnalyticsSessionsData.initialize(
      this,
      period,
      sessions,
      uniqueDevices,
      totalBytes
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, period, sessions, uniqueDevices, totalBytes) {
    obj["period"] = period;
    obj["sessions"] = sessions;
    obj["unique_devices"] = uniqueDevices;
    obj["total_bytes"] = totalBytes;
  }

  /**
   * Constructs a <code>AnalyticsSessionsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalyticsSessionsData} obj Optional instance to populate.
   * @return {module:model/AnalyticsSessionsData} The populated <code>AnalyticsSessionsData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnalyticsSessionsData();

      if (data.hasOwnProperty("period")) {
        obj["period"] = ApiClient.convertToType(data["period"], "Date");
      }
      if (data.hasOwnProperty("sessions")) {
        obj["sessions"] = ApiClient.convertToType(data["sessions"], "Number");
      }
      if (data.hasOwnProperty("unique_devices")) {
        obj["unique_devices"] = ApiClient.convertToType(
          data["unique_devices"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_bytes")) {
        obj["total_bytes"] = ApiClient.convertToType(
          data["total_bytes"],
          "Number"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>AnalyticsSessionsData</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalyticsSessionsData</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of AnalyticsSessionsData.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }

    return true;
  }
}

AnalyticsSessionsData.RequiredProperties = [
  "period",
  "sessions",
  "unique_devices",
  "total_bytes",
];

/**
 * @member {Date} period
 */
AnalyticsSessionsData.prototype["period"] = undefined;

/**
 * @member {Number} sessions
 */
AnalyticsSessionsData.prototype["sessions"] = undefined;

/**
 * @member {Number} unique_devices
 */
AnalyticsSessionsData.prototype["unique_devices"] = undefined;

/**
 * @member {Number} total_bytes
 */
AnalyticsSessionsData.prototype["total_bytes"] = undefined;

export default AnalyticsSessionsData;
