/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The ArchiveStats model module.
 * @module model/ArchiveStats
 * @version 6.6.0
 */
class ArchiveStats {
  /**
   * Constructs a new <code>ArchiveStats</code>.
   * Statistics about a repository&#39;s data archive.
   * @alias module:model/ArchiveStats
   */
  constructor() {
    ArchiveStats.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ArchiveStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArchiveStats} obj Optional instance to populate.
   * @return {module:model/ArchiveStats} The populated <code>ArchiveStats</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArchiveStats();

      if (data.hasOwnProperty("begin")) {
        obj["begin"] = ApiClient.convertToType(data["begin"], "Date");
      }
      if (data.hasOwnProperty("end")) {
        obj["end"] = ApiClient.convertToType(data["end"], "Date");
      }
      if (data.hasOwnProperty("file_count")) {
        obj["file_count"] = ApiClient.convertToType(
          data["file_count"],
          "Number"
        );
      }
      if (data.hasOwnProperty("record_count")) {
        obj["record_count"] = ApiClient.convertToType(
          data["record_count"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_size_bytes")) {
        obj["total_size_bytes"] = ApiClient.convertToType(
          data["total_size_bytes"],
          "Number"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ArchiveStats</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArchiveStats</code>.
   */
  static validateJSON(data) {
    return true;
  }
}

/**
 * Timestamp of the earliest archived record.
 * @member {Date} begin
 */
ArchiveStats.prototype["begin"] = undefined;

/**
 * Timestamp of the latest archived record.
 * @member {Date} end
 */
ArchiveStats.prototype["end"] = undefined;

/**
 * Number of archive files.
 * @member {Number} file_count
 */
ArchiveStats.prototype["file_count"] = undefined;

/**
 * Total number of records across all archive files. Null when the count cannot be determined because one or more archive files predate the record-count filename format.
 * @member {Number} record_count
 */
ArchiveStats.prototype["record_count"] = undefined;

/**
 * Total size of all archive files, in bytes.
 * @member {Number} total_size_bytes
 */
ArchiveStats.prototype["total_size_bytes"] = undefined;

export default ArchiveStats;
