/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class AWSRoleConfig {
  "aws_account_id": string;
  "external_id": string;

  static constructFromObject(data: any, obj?: AWSRoleConfig): AWSRoleConfig;
  static validateJSON(data: any): boolean;
}

export default AWSRoleConfig;
