/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class AWSRoleConfig {
  constructor(awsAccountId: string, externalId: string);

  "aws_account_id": string;
  "external_id": string;

  static constructFromObject(data: any, obj?: AWSRoleConfig): AWSRoleConfig;
  static validateJSON(data: any): boolean;
}

export default AWSRoleConfig;
