/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class BatchJobRequests {
  constructor();

  "comment"?: string;
  "connectivity_assurance_disable"?: boolean;
  "connectivity_assurance_enable"?: boolean;
  "disable"?: boolean;
  "enable"?: boolean;
  "fleets_to_default"?: string[];
  "fleets_to_join"?: string[];
  "fleets_to_leave"?: string[];
  "provision_product"?: string;
  "sn_to_default"?: string;
  "sn_to_set"?: string;
  "vars_to_default"?: { [key: string]: string };
  "vars_to_set"?: { [key: string]: string };

  static constructFromObject(
    data: any,
    obj?: BatchJobRequests,
  ): BatchJobRequests;
  static validateJSON(data: any): boolean;
}

export default BatchJobRequests;
