/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The CancelJobRun200Response model module.
 * @module model/CancelJobRun200Response
 * @version 6.2.0
 */
class CancelJobRun200Response {
  /**
   * Constructs a new <code>CancelJobRun200Response</code>.
   * @alias module:model/CancelJobRun200Response
   * @param successful {Boolean} True if cancellation was successful
   */
  constructor(successful) {
    CancelJobRun200Response.initialize(this, successful);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, successful) {
    obj["successful"] = successful;
  }

  /**
   * Constructs a <code>CancelJobRun200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancelJobRun200Response} obj Optional instance to populate.
   * @return {module:model/CancelJobRun200Response} The populated <code>CancelJobRun200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CancelJobRun200Response();

      if (data.hasOwnProperty("successful")) {
        obj["successful"] = ApiClient.convertToType(
          data["successful"],
          "Boolean"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>CancelJobRun200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CancelJobRun200Response</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of CancelJobRun200Response.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }

    return true;
  }
}

CancelJobRun200Response.RequiredProperties = ["successful"];

/**
 * True if cancellation was successful
 * @member {Boolean} successful
 */
CancelJobRun200Response.prototype["successful"] = undefined;

export default CancelJobRun200Response;
