/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The CreateJob201Response model module.
 * @module model/CreateJob201Response
 * @version 6.1.0
 */
class CreateJob201Response {
  /**
   * Constructs a new <code>CreateJob201Response</code>.
   * @alias module:model/CreateJob201Response
   * @param jobUid {String} The unique identifier for the created job
   */
  constructor(jobUid) {
    CreateJob201Response.initialize(this, jobUid);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, jobUid) {
    obj["job_uid"] = jobUid;
  }

  /**
   * Constructs a <code>CreateJob201Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateJob201Response} obj Optional instance to populate.
   * @return {module:model/CreateJob201Response} The populated <code>CreateJob201Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateJob201Response();

      if (data.hasOwnProperty("job_uid")) {
        obj["job_uid"] = ApiClient.convertToType(data["job_uid"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>CreateJob201Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateJob201Response</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of CreateJob201Response.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    // ensure the json data is a string
    if (
      data["job_uid"] &&
      !(
        typeof data["job_uid"] === "string" || data["job_uid"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `job_uid` to be a primitive type in the JSON string but got " +
          data["job_uid"]
      );
    }

    return true;
  }
}

CreateJob201Response.RequiredProperties = ["job_uid"];

/**
 * The unique identifier for the created job
 * @member {String} job_uid
 */
CreateJob201Response.prototype["job_uid"] = undefined;

export default CreateJob201Response;
