/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import MonitorAlertRoutesInner from "../model/MonitorAlertRoutesInner";

declare class CreateMonitor {
  "aggregate_function"?: "none" | "sum" | "average" | "max" | "min";
  "aggregate_window"?: string;
  "alert"?: boolean;
  "alert_routes": MonitorAlertRoutesInner[];
  "condition_type"?:
    | "greater_than"
    | "greater_than_or_equal_to"
    | "less_than"
    | "less_than_or_equal_to"
    | "equal_to"
    | "not_equal_to"
    | "count";
  "description": string;
  "disabled"?: boolean;
  "fleet_filter"?: string[];
  "last_routed_at"?: string;
  "name": string;
  "notefile_filter"?: string[];
  "per_device"?: boolean;
  "routing_cooldown_period"?: string;
  "silenced"?: boolean;
  "source_selector"?: string;
  "source_type": "event" | "heartbeat";
  "threshold": number;
  "uid"?: string;
  "usage_scope"?: string;
  "usage_type"?: string;
  "usage_window"?: number;

  static readonly AggregateFunctionEnum: {
    none: "none";
    sum: "sum";
    average: "average";
    max: "max";
    min: "min";
  };
  static readonly ConditionTypeEnum: {
    greater_than: "greater_than";
    greater_than_or_equal_to: "greater_than_or_equal_to";
    less_than: "less_than";
    less_than_or_equal_to: "less_than_or_equal_to";
    equal_to: "equal_to";
    not_equal_to: "not_equal_to";
    count: "count";
  };
  static readonly SourceTypeEnum: { event: "event"; heartbeat: "heartbeat" };

  static constructFromObject(data: any, obj?: CreateMonitor): CreateMonitor;
  static validateJSON(data: any): boolean;
}

export default CreateMonitor;
