/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class CreateProjectRequest {
  constructor(billingAccountUid: string, label: string);

  "billing_account_uid": string;
  "label": string;

  static constructFromObject(
    data: any,
    obj?: CreateProjectRequest,
  ): CreateProjectRequest;
  static validateJSON(data: any): boolean;
}

export default CreateProjectRequest;
