/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class CreateProductRequest {
  constructor(label: string, productUid: string);

  "auto_provision_fleets"?: string[];
  "disable_devices_by_default"?: boolean;
  "label": string;
  "product_uid": string;

  static constructFromObject(
    data: any,
    obj?: CreateProductRequest,
  ): CreateProductRequest;
  static validateJSON(data: any): boolean;
}

export default CreateProductRequest;
