/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class DeleteDeviceFromFleetsRequest {
  constructor(fleetUids: string[]);

  "fleet_uids": string[];

  static constructFromObject(
    data: any,
    obj?: DeleteDeviceFromFleetsRequest,
  ): DeleteDeviceFromFleetsRequest;
  static validateJSON(data: any): boolean;
}

export default DeleteDeviceFromFleetsRequest;
