/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The DeleteJob200Response model module.
 * @module model/DeleteJob200Response
 * @version 6.2.0
 */
class DeleteJob200Response {
  /**
   * Constructs a new <code>DeleteJob200Response</code>.
   * @alias module:model/DeleteJob200Response
   * @param success {Boolean} True if deletion was successful
   */
  constructor(success) {
    DeleteJob200Response.initialize(this, success);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, success) {
    obj["success"] = success;
  }

  /**
   * Constructs a <code>DeleteJob200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteJob200Response} obj Optional instance to populate.
   * @return {module:model/DeleteJob200Response} The populated <code>DeleteJob200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeleteJob200Response();

      if (data.hasOwnProperty("success")) {
        obj["success"] = ApiClient.convertToType(data["success"], "Boolean");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>DeleteJob200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteJob200Response</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of DeleteJob200Response.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }

    return true;
  }
}

DeleteJob200Response.RequiredProperties = ["success"];

/**
 * True if deletion was successful
 * @member {Boolean} success
 */
DeleteJob200Response.prototype["success"] = undefined;

export default DeleteJob200Response;
