import DeviceDfuStatus from "../model/DeviceDfuStatus";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class DeviceDfuStatusPage {
  constructor();

  "devices"?: DeviceDfuStatus[];
  "has_more"?: boolean;

  static constructFromObject(
    data: any,
    obj?: DeviceDfuStatusPage,
  ): DeviceDfuStatusPage;
  static validateJSON(data: any): boolean;
}

export default DeviceDfuStatusPage;
