/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The DeviceSensor model module.
 * @module model/DeviceSensor
 * @version 6.6.0
 */
class DeviceSensor {
  /**
   * Constructs a new <code>DeviceSensor</code>.
   * A sensor attached to a device
   * @alias module:model/DeviceSensor
   * @param sensorUid {String} Unique identifier of the sensor
   */
  constructor(sensorUid) {
    DeviceSensor.initialize(this, sensorUid);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, sensorUid) {
    obj["sensor_uid"] = sensorUid;
  }

  /**
   * Constructs a <code>DeviceSensor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceSensor} obj Optional instance to populate.
   * @return {module:model/DeviceSensor} The populated <code>DeviceSensor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceSensor();

      if (data.hasOwnProperty("last_activity_date")) {
        obj["last_activity_date"] = ApiClient.convertToType(
          data["last_activity_date"],
          "Date"
        );
      }
      if (data.hasOwnProperty("sensor_uid")) {
        obj["sensor_uid"] = ApiClient.convertToType(
          data["sensor_uid"],
          "String"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>DeviceSensor</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeviceSensor</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of DeviceSensor.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    // ensure the json data is a string
    if (
      data["sensor_uid"] &&
      !(
        typeof data["sensor_uid"] === "string" ||
        data["sensor_uid"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `sensor_uid` to be a primitive type in the JSON string but got " +
          data["sensor_uid"]
      );
    }

    return true;
  }
}

DeviceSensor.RequiredProperties = ["sensor_uid"];

/**
 * UTC midnight of the most recent day on which this sensor was active
 * @member {Date} last_activity_date
 */
DeviceSensor.prototype["last_activity_date"] = undefined;

/**
 * Unique identifier of the sensor
 * @member {String} sensor_uid
 */
DeviceSensor.prototype["sensor_uid"] = undefined;

export default DeviceSensor;
