/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class DeviceDfuHistoryCurrent {
  constructor();

  "builder"?: string;
  "built"?: string;
  "description"?: string;
  "organization"?: string;
  "product"?: string;
  "version"?: string;

  static constructFromObject(
    data: any,
    obj?: DeviceDfuHistoryCurrent,
  ): DeviceDfuHistoryCurrent;
  static validateJSON(data: any): boolean;
}

export default DeviceDfuHistoryCurrent;
