/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class DeviceTowerInfo {
  constructor();

  "cell_id"?: number;
  "lac"?: number;
  "mcc"?: number;
  "mnc"?: number;

  static constructFromObject(data: any, obj?: DeviceTowerInfo): DeviceTowerInfo;
  static validateJSON(data: any): boolean;
}

export default DeviceTowerInfo;
