import DFUState from "../model/DFUState";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class DFUEnv {
  constructor();

  "card"?: DFUState;
  "user"?: DFUState;

  static constructFromObject(data: any, obj?: DFUEnv): DFUEnv;
  static validateJSON(data: any): boolean;
}

export default DFUEnv;
