/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class DFUState {
  "began"?: number;
  "crc32"?: number;
  "errors"?: number;
  "file"?: string;
  "length"?: number;
  "md5"?: string;
  "mode"?:
    | "idle"
    | "error"
    | "downloading"
    | "sideloading"
    | "ready"
    | "updating"
    | "completed";
  "read"?: number;
  "retry"?: number;
  "status"?: string;
  "type"?: "card" | "user";
  "updated"?: number;
  "version"?: string;

  static readonly ModeEnum: {
    idle: "idle";
    error: "error";
    downloading: "downloading";
    sideloading: "sideloading";
    ready: "ready";
    updating: "updating";
    completed: "completed";
  };
  static readonly TypeEnum: { card: "card"; user: "user" };

  static constructFromObject(data: any, obj?: DFUState): DFUState;
  static validateJSON(data: any): boolean;
}

export default DFUState;
