/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import EnvVar from "../model/EnvVar";

declare class EnvTreeJsonNode {
  constructor(
    children: EnvTreeJsonNode[],
    inheritedVarCount: number,
    type: string,
    varCount: number,
    variables: EnvVar[],
  );

  "app_label"?: string;
  "app_uid"?: string;
  "children": EnvTreeJsonNode[];
  "device_uid"?: string;
  "fleet_label"?: string;
  "fleet_uid"?: string;
  "inherited_var_count": number;
  "type": string;
  "url"?: string;
  "var_count": number;
  "variables": EnvVar[];

  static constructFromObject(data: any, obj?: EnvTreeJsonNode): EnvTreeJsonNode;
  static validateJSON(data: any): boolean;
}

export default EnvTreeJsonNode;
