/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class Error {
  "code": number;
  "debug"?: string;
  "details"?: { [key: string]: any };
  "err": string;
  "request"?: string;
  "status": string;

  static constructFromObject(data: any, obj?: Error): Error;
  static validateJSON(data: any): boolean;
}

export default Error;
