/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class Event {
  constructor();

  "app"?: string;
  "bars"?: number;
  "best_country"?: string;
  "best_id"?: string;
  "best_lat"?: number;
  "best_location"?: string;
  "best_location_type"?: string;
  "best_location_when"?: number;
  "best_lon"?: number;
  "best_timezone"?: string;
  "body"?: { [key: string]: any };
  "bssid"?: string;
  "device"?: string;
  "environment"?: { [key: string]: any };
  "event"?: string;
  "file"?: string;
  "moved"?: number;
  "note"?: string;
  "ordering_code"?: string;
  "orientation"?: string;
  "payload"?: string;
  "product"?: string;
  "rat"?: string;
  "received"?: number;
  "req"?: string;
  "rsrp"?: number;
  "rsrq"?: number;
  "rssi"?: number;
  "session"?: string;
  "sinr"?: number;
  "sku"?: string;
  "sn"?: string;
  "ssid"?: string;
  "temp"?: number;
  "tls"?: boolean;
  "tower_country"?: string;
  "tower_id"?: string;
  "tower_lat"?: number;
  "tower_location"?: string;
  "tower_lon"?: number;
  "tower_timezone"?: string;
  "tower_when"?: number;
  "transport"?: string;
  "tri_country"?: string;
  "tri_lat"?: number;
  "tri_location"?: string;
  "tri_lon"?: number;
  "tri_points"?: number;
  "tri_timezone"?: string;
  "tri_when"?: number;
  "updates"?: number;
  "voltage"?: number;
  "when"?: number;
  "where_country"?: string;
  "where_lat"?: number;
  "where_location"?: string;
  "where_lon"?: number;
  "where_olc"?: string;
  "where_timezone"?: string;
  "where_when"?: number;

  static constructFromObject(data: any, obj?: Event): Event;
  static validateJSON(data: any): boolean;
}

export default Event;
