/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import UsageApiData from "./UsageApiData";

/**
 * The GetApiUsage200Response model module.
 * @module model/GetApiUsage200Response
 * @version 6.7.0
 */
class GetApiUsage200Response {
  /**
   * Constructs a new <code>GetApiUsage200Response</code>.
   * @alias module:model/GetApiUsage200Response
   * @param data {Array.<module:model/UsageApiData>}
   */
  constructor(data) {
    GetApiUsage200Response.initialize(this, data);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, data) {
    obj["data"] = data;
  }

  /**
   * Constructs a <code>GetApiUsage200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetApiUsage200Response} obj Optional instance to populate.
   * @return {module:model/GetApiUsage200Response} The populated <code>GetApiUsage200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetApiUsage200Response();

      if (data.hasOwnProperty("data")) {
        obj["data"] = ApiClient.convertToType(data["data"], [UsageApiData]);
      }
      if (data.hasOwnProperty("truncated")) {
        obj["truncated"] = ApiClient.convertToType(
          data["truncated"],
          "Boolean"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetApiUsage200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApiUsage200Response</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of GetApiUsage200Response.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    if (data["data"]) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data["data"])) {
        throw new Error(
          "Expected the field `data` to be an array in the JSON data but got " +
            data["data"]
        );
      }
      // validate the optional field `data` (array)
      for (const item of data["data"]) {
        UsageApiData.validateJsonObject(item);
      }
    }

    return true;
  }
}

GetApiUsage200Response.RequiredProperties = ["data"];

/**
 * @member {Array.<module:model/UsageApiData>} data
 */
GetApiUsage200Response.prototype["data"] = undefined;

/**
 * If the data is truncated that means that the parameters selected resulted in a response of over | the requested limit of data points, in order to ensure
 * @member {Boolean} truncated
 */
GetApiUsage200Response.prototype["truncated"] = undefined;

export default GetApiUsage200Response;
