/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The GetBillingAccountBalanceHistory200ResponseDataInner model module.
 * @module model/GetBillingAccountBalanceHistory200ResponseDataInner
 * @version 6.2.0
 */
class GetBillingAccountBalanceHistory200ResponseDataInner {
  /**
   * Constructs a new <code>GetBillingAccountBalanceHistory200ResponseDataInner</code>.
   * @alias module:model/GetBillingAccountBalanceHistory200ResponseDataInner
   * @param period {Date}
   * @param remainingEventCapacity {Number}
   * @param totalEventCapacityUsed {Number}
   */
  constructor(period, remainingEventCapacity, totalEventCapacityUsed) {
    GetBillingAccountBalanceHistory200ResponseDataInner.initialize(
      this,
      period,
      remainingEventCapacity,
      totalEventCapacityUsed
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    period,
    remainingEventCapacity,
    totalEventCapacityUsed
  ) {
    obj["period"] = period;
    obj["remaining_event_capacity"] = remainingEventCapacity;
    obj["total_event_capacity_used"] = totalEventCapacityUsed;
  }

  /**
   * Constructs a <code>GetBillingAccountBalanceHistory200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBillingAccountBalanceHistory200ResponseDataInner} obj Optional instance to populate.
   * @return {module:model/GetBillingAccountBalanceHistory200ResponseDataInner} The populated <code>GetBillingAccountBalanceHistory200ResponseDataInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetBillingAccountBalanceHistory200ResponseDataInner();

      if (data.hasOwnProperty("period")) {
        obj["period"] = ApiClient.convertToType(data["period"], "Date");
      }
      if (data.hasOwnProperty("remaining_event_capacity")) {
        obj["remaining_event_capacity"] = ApiClient.convertToType(
          data["remaining_event_capacity"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_event_capacity_used")) {
        obj["total_event_capacity_used"] = ApiClient.convertToType(
          data["total_event_capacity_used"],
          "Number"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetBillingAccountBalanceHistory200ResponseDataInner</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetBillingAccountBalanceHistory200ResponseDataInner</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of GetBillingAccountBalanceHistory200ResponseDataInner.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }

    return true;
  }
}

GetBillingAccountBalanceHistory200ResponseDataInner.RequiredProperties = [
  "period",
  "remaining_event_capacity",
  "total_event_capacity_used",
];

/**
 * @member {Date} period
 */
GetBillingAccountBalanceHistory200ResponseDataInner.prototype["period"] =
  undefined;

/**
 * @member {Number} remaining_event_capacity
 */
GetBillingAccountBalanceHistory200ResponseDataInner.prototype[
  "remaining_event_capacity"
] = undefined;

/**
 * @member {Number} total_event_capacity_used
 */
GetBillingAccountBalanceHistory200ResponseDataInner.prototype[
  "total_event_capacity_used"
] = undefined;

export default GetBillingAccountBalanceHistory200ResponseDataInner;
