import BillingAccount from "../model/BillingAccount";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetBillingAccounts200Response {
  constructor();

  "billing_accounts"?: BillingAccount[];

  static constructFromObject(
    data: any,
    obj?: GetBillingAccounts200Response,
  ): GetBillingAccounts200Response;
  static validateJSON(data: any): boolean;
}

export default GetBillingAccounts200Response;
