/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import GetBillingAccountBalanceHistory200ResponseDataInner from "./GetBillingAccountBalanceHistory200ResponseDataInner";

/**
 * The GetBillingAccountBalanceHistory200Response model module.
 * @module model/GetBillingAccountBalanceHistory200Response
 * @version 6.1.0
 */
class GetBillingAccountBalanceHistory200Response {
  /**
   * Constructs a new <code>GetBillingAccountBalanceHistory200Response</code>.
   * @alias module:model/GetBillingAccountBalanceHistory200Response
   */
  constructor() {
    GetBillingAccountBalanceHistory200Response.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>GetBillingAccountBalanceHistory200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBillingAccountBalanceHistory200Response} obj Optional instance to populate.
   * @return {module:model/GetBillingAccountBalanceHistory200Response} The populated <code>GetBillingAccountBalanceHistory200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetBillingAccountBalanceHistory200Response();

      if (data.hasOwnProperty("data")) {
        obj["data"] = ApiClient.convertToType(data["data"], [
          GetBillingAccountBalanceHistory200ResponseDataInner,
        ]);
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetBillingAccountBalanceHistory200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetBillingAccountBalanceHistory200Response</code>.
   */
  static validateJSON(data) {
    if (data["data"]) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data["data"])) {
        throw new Error(
          "Expected the field `data` to be an array in the JSON data but got " +
            data["data"]
        );
      }
      // validate the optional field `data` (array)
      for (const item of data["data"]) {
        GetBillingAccountBalanceHistory200ResponseDataInner.validateJsonObject(
          item
        );
      }
    }

    return true;
  }
}

/**
 * @member {Array.<module:model/GetBillingAccountBalanceHistory200ResponseDataInner>} data
 */
GetBillingAccountBalanceHistory200Response.prototype["data"] = undefined;

export default GetBillingAccountBalanceHistory200Response;
