/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import GetBillingAccount200ResponsePlan from "./GetBillingAccount200ResponsePlan";

/**
 * The GetBillingAccount200Response model module.
 * @module model/GetBillingAccount200Response
 * @version 6.1.0
 */
class GetBillingAccount200Response {
  /**
   * Constructs a new <code>GetBillingAccount200Response</code>.
   * @alias module:model/GetBillingAccount200Response
   */
  constructor() {
    GetBillingAccount200Response.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>GetBillingAccount200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBillingAccount200Response} obj Optional instance to populate.
   * @return {module:model/GetBillingAccount200Response} The populated <code>GetBillingAccount200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetBillingAccount200Response();

      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
      if (data.hasOwnProperty("owner")) {
        obj["owner"] = ApiClient.convertToType(data["owner"], "String");
      }
      if (data.hasOwnProperty("plan")) {
        obj["plan"] = GetBillingAccount200ResponsePlan.constructFromObject(
          data["plan"]
        );
      }
      if (data.hasOwnProperty("suspended")) {
        obj["suspended"] = ApiClient.convertToType(
          data["suspended"],
          "Boolean"
        );
      }
      if (data.hasOwnProperty("uid")) {
        obj["uid"] = ApiClient.convertToType(data["uid"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetBillingAccount200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetBillingAccount200Response</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["name"] &&
      !(typeof data["name"] === "string" || data["name"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `name` to be a primitive type in the JSON string but got " +
          data["name"]
      );
    }
    // ensure the json data is a string
    if (
      data["owner"] &&
      !(typeof data["owner"] === "string" || data["owner"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `owner` to be a primitive type in the JSON string but got " +
          data["owner"]
      );
    }
    // validate the optional field `plan`
    if (data["plan"]) {
      // data not null
      GetBillingAccount200ResponsePlan.validateJSON(data["plan"]);
    }
    // ensure the json data is a string
    if (
      data["uid"] &&
      !(typeof data["uid"] === "string" || data["uid"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `uid` to be a primitive type in the JSON string but got " +
          data["uid"]
      );
    }

    return true;
  }
}

/**
 * @member {String} name
 */
GetBillingAccount200Response.prototype["name"] = undefined;

/**
 * @member {String} owner
 */
GetBillingAccount200Response.prototype["owner"] = undefined;

/**
 * @member {module:model/GetBillingAccount200ResponsePlan} plan
 */
GetBillingAccount200Response.prototype["plan"] = undefined;

/**
 * @member {Boolean} suspended
 */
GetBillingAccount200Response.prototype["suspended"] = undefined;

/**
 * @member {String} uid
 */
GetBillingAccount200Response.prototype["uid"] = undefined;

export default GetBillingAccount200Response;
