import GetDevicePublicKeys200ResponseDevicePublicKeysInner from "../model/GetDevicePublicKeys200ResponseDevicePublicKeysInner";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetDevicePublicKeys200Response {
  constructor(
    devicePublicKeys: GetDevicePublicKeys200ResponseDevicePublicKeysInner[],
    hasMore: boolean,
  );

  "device_public_keys": GetDevicePublicKeys200ResponseDevicePublicKeysInner[];
  "has_more": boolean;

  static constructFromObject(
    data: any,
    obj?: GetDevicePublicKeys200Response,
  ): GetDevicePublicKeys200Response;
  static validateJSON(data: any): boolean;
}

export default GetDevicePublicKeys200Response;
