/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class GetDevicePublicKey200Response {
  "key": string;
  "uid": string;

  static constructFromObject(
    data: any,
    obj?: GetDevicePublicKey200Response,
  ): GetDevicePublicKey200Response;
  static validateJSON(data: any): boolean;
}

export default GetDevicePublicKey200Response;
