/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetDbNote200Response {
  constructor();

  "body"?: { [key: string]: any };
  "payload"?: string;
  "time"?: number;

  static constructFromObject(
    data: any,
    obj?: GetDbNote200Response,
  ): GetDbNote200Response;
  static validateJSON(data: any): boolean;
}

export default GetDbNote200Response;
