import GetDataUsage200ResponseDataInner from "../model/GetDataUsage200ResponseDataInner";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetDataUsage200Response {
  constructor();

  "data"?: GetDataUsage200ResponseDataInner[];
  "truncated"?: boolean;

  static constructFromObject(
    data: any,
    obj?: GetDataUsage200Response,
  ): GetDataUsage200Response;
  static validateJSON(data: any): boolean;
}

export default GetDataUsage200Response;
