/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetDevicePublicKeys200ResponseDevicePublicKeysInner {
  constructor();

  "key"?: string;
  "uid"?: string;

  static constructFromObject(
    data: any,
    obj?: GetDevicePublicKeys200ResponseDevicePublicKeysInner,
  ): GetDevicePublicKeys200ResponseDevicePublicKeysInner;
  static validateJSON(data: any): boolean;
}

export default GetDevicePublicKeys200ResponseDevicePublicKeysInner;
