/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import GetDataUsage200ResponseDataInner from "../model/GetDataUsage200ResponseDataInner";

declare class GetDataUsage200Response {
  constructor();

  "data"?: GetDataUsage200ResponseDataInner[];
  "truncated"?: boolean;

  static constructFromObject(
    data: any,
    obj?: GetDataUsage200Response,
  ): GetDataUsage200Response;
  static validateJSON(data: any): boolean;
}

export default GetDataUsage200Response;
