/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import GetDeviceJourneys200ResponseJourneysInner from "../model/GetDeviceJourneys200ResponseJourneysInner";

declare class GetDeviceJourneys200Response {
  constructor(
    hasMore: boolean,
    journeys: GetDeviceJourneys200ResponseJourneysInner[],
  );

  "has_more": boolean;
  "journeys": GetDeviceJourneys200ResponseJourneysInner[];

  static constructFromObject(
    data: any,
    obj?: GetDeviceJourneys200Response,
  ): GetDeviceJourneys200Response;
  static validateJSON(data: any): boolean;
}

export default GetDeviceJourneys200Response;
