import Event from "../model/Event";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GetEvents200Response {
  constructor(events: Event[], hasMore: boolean);

  "events": Event[];
  "has_more": boolean;
  "through"?: string;

  static constructFromObject(
    data: any,
    obj?: GetEvents200Response,
  ): GetEvents200Response;
  static validateJSON(data: any): boolean;
}

export default GetEvents200Response;
