/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import Organization from "../model/Organization";

declare class GetOrganizations200Response {
  "organizations"?: Organization[];

  static constructFromObject(
    data: any,
    obj?: GetOrganizations200Response,
  ): GetOrganizations200Response;
  static validateJSON(data: any): boolean;
}

export default GetOrganizations200Response;
