/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Product from "./Product";

/**
 * The GetProducts200Response model module.
 * @module model/GetProducts200Response
 * @version 2.3.0
 */
class GetProducts200Response {
  /**
   * Constructs a new <code>GetProducts200Response</code>.
   * @alias module:model/GetProducts200Response
   */
  constructor() {
    GetProducts200Response.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>GetProducts200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetProducts200Response} obj Optional instance to populate.
   * @return {module:model/GetProducts200Response} The populated <code>GetProducts200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetProducts200Response();

      if (data.hasOwnProperty("products")) {
        obj["products"] = ApiClient.convertToType(data["products"], [Product]);
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetProducts200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProducts200Response</code>.
   */
  static validateJSON(data) {
    if (data["products"]) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data["products"])) {
        throw new Error(
          "Expected the field `products` to be an array in the JSON data but got " +
            data["products"]
        );
      }
      // validate the optional field `products` (array)
      for (const item of data["products"]) {
        Product.validateJsonObject(item);
      }
    }

    return true;
  }
}

/**
 * @member {Array.<module:model/Product>} products
 */
GetProducts200Response.prototype["products"] = undefined;

export default GetProducts200Response;
