/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ProjectSecret from "./ProjectSecret";

/**
 * The GetProjectSecretsResponse model module.
 * @module model/GetProjectSecretsResponse
 * @version 6.3.0
 */
class GetProjectSecretsResponse {
  /**
   * Constructs a new <code>GetProjectSecretsResponse</code>.
   * @alias module:model/GetProjectSecretsResponse
   * @param secrets {Array.<module:model/ProjectSecret>}
   */
  constructor(secrets) {
    GetProjectSecretsResponse.initialize(this, secrets);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, secrets) {
    obj["secrets"] = secrets;
  }

  /**
   * Constructs a <code>GetProjectSecretsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetProjectSecretsResponse} obj Optional instance to populate.
   * @return {module:model/GetProjectSecretsResponse} The populated <code>GetProjectSecretsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetProjectSecretsResponse();

      if (data.hasOwnProperty("secrets")) {
        obj["secrets"] = ApiClient.convertToType(data["secrets"], [
          ProjectSecret,
        ]);
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>GetProjectSecretsResponse</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProjectSecretsResponse</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of GetProjectSecretsResponse.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    if (data["secrets"]) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data["secrets"])) {
        throw new Error(
          "Expected the field `secrets` to be an array in the JSON data but got " +
            data["secrets"]
        );
      }
      // validate the optional field `secrets` (array)
      for (const item of data["secrets"]) {
        ProjectSecret.validateJsonObject(item);
      }
    }

    return true;
  }
}

GetProjectSecretsResponse.RequiredProperties = ["secrets"];

/**
 * @member {Array.<module:model/ProjectSecret>} secrets
 */
GetProjectSecretsResponse.prototype["secrets"] = undefined;

export default GetProjectSecretsResponse;
