/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import WebhookSettings from "../model/WebhookSettings";

declare class GetWebhooks200Response {
  "webhooks"?: WebhookSettings[];

  static constructFromObject(
    data: any,
    obj?: GetWebhooks200Response,
  ): GetWebhooks200Response;
  static validateJSON(data: any): boolean;
}

export default GetWebhooks200Response;
