import Filter from "../model/Filter";
import RouteTransformSettings from "../model/RouteTransformSettings";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class GoogleRoute {
  constructor();

  "filter"?: Filter;
  "fleets"?: string[];
  "throttle_ms"?: number;
  "timeout"?: number;
  "token"?: string;
  "transform"?: RouteTransformSettings;
  "url"?: string;

  static constructFromObject(data: any, obj?: GoogleRoute): GoogleRoute;
  static validateJSON(data: any): boolean;
}

export default GoogleRoute;
