/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The Job model module.
 * @module model/Job
 * @version 6.1.0
 */
class Job {
  /**
   * Constructs a new <code>Job</code>.
   * @alias module:model/Job
   * @param created {Number} Unix timestamp when job was created
   * @param createdBy {String} User who created the job
   * @param jobUid {String} Unique identifier for the job
   * @param name {String} Human-readable job name
   */
  constructor(created, createdBy, jobUid, name) {
    Job.initialize(this, created, createdBy, jobUid, name);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, created, createdBy, jobUid, name) {
    obj["created"] = created;
    obj["created_by"] = createdBy;
    obj["job_uid"] = jobUid;
    obj["name"] = name;
  }

  /**
   * Constructs a <code>Job</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Job} obj Optional instance to populate.
   * @return {module:model/Job} The populated <code>Job</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Job();

      if (data.hasOwnProperty("created")) {
        obj["created"] = ApiClient.convertToType(data["created"], "Number");
      }
      if (data.hasOwnProperty("created_by")) {
        obj["created_by"] = ApiClient.convertToType(
          data["created_by"],
          "String"
        );
      }
      if (data.hasOwnProperty("definition")) {
        obj["definition"] = ApiClient.convertToType(data["definition"], {
          String: Object,
        });
      }
      if (data.hasOwnProperty("job_uid")) {
        obj["job_uid"] = ApiClient.convertToType(data["job_uid"], "String");
      }
      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>Job</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Job</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of Job.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    // ensure the json data is a string
    if (
      data["created_by"] &&
      !(
        typeof data["created_by"] === "string" ||
        data["created_by"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `created_by` to be a primitive type in the JSON string but got " +
          data["created_by"]
      );
    }
    // ensure the json data is a string
    if (
      data["job_uid"] &&
      !(
        typeof data["job_uid"] === "string" || data["job_uid"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `job_uid` to be a primitive type in the JSON string but got " +
          data["job_uid"]
      );
    }
    // ensure the json data is a string
    if (
      data["name"] &&
      !(typeof data["name"] === "string" || data["name"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `name` to be a primitive type in the JSON string but got " +
          data["name"]
      );
    }

    return true;
  }
}

Job.RequiredProperties = ["created", "created_by", "job_uid", "name"];

/**
 * Unix timestamp when job was created
 * @member {Number} created
 */
Job.prototype["created"] = undefined;

/**
 * User who created the job
 * @member {String} created_by
 */
Job.prototype["created_by"] = undefined;

/**
 * Full job definition (only in detail view)
 * @member {Object.<String, Object>} definition
 */
Job.prototype["definition"] = undefined;

/**
 * Unique identifier for the job
 * @member {String} job_uid
 */
Job.prototype["job_uid"] = undefined;

/**
 * Human-readable job name
 * @member {String} name
 */
Job.prototype["name"] = undefined;

export default Job;
