/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import BatchJobRequests from "./BatchJobRequests";
import JobDefinitionReportOptions from "./JobDefinitionReportOptions";
import JobDefinitionSelect from "./JobDefinitionSelect";

/**
 * The JobDefinition model module.
 * @module model/JobDefinition
 * @version 6.4.0
 */
class JobDefinition {
  /**
   * Constructs a new <code>JobDefinition</code>.
   * Batch job definition
   * @alias module:model/JobDefinition
   */
  constructor() {
    JobDefinition.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>JobDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JobDefinition} obj Optional instance to populate.
   * @return {module:model/JobDefinition} The populated <code>JobDefinition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JobDefinition();

      if (data.hasOwnProperty("comment")) {
        obj["comment"] = ApiClient.convertToType(data["comment"], "String");
      }
      if (data.hasOwnProperty("default_requests")) {
        obj["default_requests"] = BatchJobRequests.constructFromObject(
          data["default_requests"]
        );
      }
      if (data.hasOwnProperty("device_requests")) {
        obj["device_requests"] = ApiClient.convertToType(
          data["device_requests"],
          { String: BatchJobRequests }
        );
      }
      if (data.hasOwnProperty("report_options")) {
        obj["report_options"] = JobDefinitionReportOptions.constructFromObject(
          data["report_options"]
        );
      }
      if (data.hasOwnProperty("select")) {
        obj["select"] = JobDefinitionSelect.constructFromObject(data["select"]);
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>JobDefinition</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobDefinition</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["comment"] &&
      !(
        typeof data["comment"] === "string" || data["comment"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `comment` to be a primitive type in the JSON string but got " +
          data["comment"]
      );
    }
    // validate the optional field `default_requests`
    if (data["default_requests"]) {
      // data not null
      BatchJobRequests.validateJSON(data["default_requests"]);
    }
    // validate the optional field `report_options`
    if (data["report_options"]) {
      // data not null
      JobDefinitionReportOptions.validateJSON(data["report_options"]);
    }
    // validate the optional field `select`
    if (data["select"]) {
      // data not null
      JobDefinitionSelect.validateJSON(data["select"]);
    }

    return true;
  }
}

/**
 * Human-readable description of the job
 * @member {String} comment
 */
JobDefinition.prototype["comment"] = undefined;

/**
 * @member {module:model/BatchJobRequests} default_requests
 */
JobDefinition.prototype["default_requests"] = undefined;

/**
 * Device-specific request overrides, keyed by device UID
 * @member {Object.<String, module:model/BatchJobRequests>} device_requests
 */
JobDefinition.prototype["device_requests"] = undefined;

/**
 * @member {module:model/JobDefinitionReportOptions} report_options
 */
JobDefinition.prototype["report_options"] = undefined;

/**
 * @member {module:model/JobDefinitionSelect} select
 */
JobDefinition.prototype["select"] = undefined;

export default JobDefinition;
