/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class Note {
  "body": { [key: string]: { [key: string]: any } };
  "edge"?: boolean;
  "id": string;
  "payload"?: Blob;
  "pending"?: boolean;
  "time": number;
  "where"?: string;

  static constructFromObject(data: any, obj?: Note): Note;
  static validateJSON(data: any): boolean;
}

export default Note;
