import OrganizationRole from "../model/OrganizationRole";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class Organization {
  constructor(name: string, role: OrganizationRole, uid: string);

  "name": string;
  "role": OrganizationRole;
  "uid": string;

  static constructFromObject(data: any, obj?: Organization): Organization;
  static validateJSON(data: any): boolean;
}

export default Organization;
