/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class PersonalAccessTokenInfo {
  constructor();

  "description"?: string;
  "expires_at"?: Date;
  "name"?: string;
  "suspended"?: boolean;

  static constructFromObject(
    data: any,
    obj?: PersonalAccessTokenInfo,
  ): PersonalAccessTokenInfo;
  static validateJSON(data: any): boolean;
}

export default PersonalAccessTokenInfo;
