import PersonalAccessTokenCreatedBy from "../model/PersonalAccessTokenCreatedBy";
/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class PersonalAccessToken {
  constructor();

  "created_at"?: Date;
  "created_by"?: PersonalAccessTokenCreatedBy;
  "description"?: string;
  "expires_at"?: Date;
  "last_used"?: Date;
  "name"?: string;
  "suspended"?: boolean;
  "uid"?: string;

  static constructFromObject(
    data: any,
    obj?: PersonalAccessToken,
  ): PersonalAccessToken;
  static validateJSON(data: any): boolean;
}

export default PersonalAccessToken;
