/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import Role from "../model/Role";

declare class ProjectMember {
  "email": string;
  "name": string;
  "role": Role;

  static constructFromObject(data: any, obj?: ProjectMember): ProjectMember;
  static validateJSON(data: any): boolean;
}

export default ProjectMember;
