/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The RepositoryTokenRequest model module.
 * @module model/RepositoryTokenRequest
 * @version 6.4.0
 */
class RepositoryTokenRequest {
  /**
   * Constructs a new <code>RepositoryTokenRequest</code>.
   * @alias module:model/RepositoryTokenRequest
   */
  constructor() {
    RepositoryTokenRequest.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>RepositoryTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RepositoryTokenRequest} obj Optional instance to populate.
   * @return {module:model/RepositoryTokenRequest} The populated <code>RepositoryTokenRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RepositoryTokenRequest();

      if (data.hasOwnProperty("intent")) {
        obj["intent"] = ApiClient.convertToType(data["intent"], "String");
      }
      if (data.hasOwnProperty("ttl_seconds")) {
        obj["ttl_seconds"] = ApiClient.convertToType(
          data["ttl_seconds"],
          "Number"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>RepositoryTokenRequest</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepositoryTokenRequest</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["intent"] &&
      !(typeof data["intent"] === "string" || data["intent"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `intent` to be a primitive type in the JSON string but got " +
          data["intent"]
      );
    }

    return true;
  }
}

/**
 * Access intent for the vended credentials. Only `read` is supported today; `write` and `admin` are reserved for future use.
 * @member {module:model/RepositoryTokenRequest.IntentEnum} intent
 * @default 'read'
 */
RepositoryTokenRequest.prototype["intent"] = "read";

/**
 * Requested credential lifetime in seconds. Clamped server-side to [60, 3600]. Defaults to 900 (15 minutes) if omitted.
 * @member {Number} ttl_seconds
 * @default 900
 */
RepositoryTokenRequest.prototype["ttl_seconds"] = 900;

/**
 * Allowed values for the <code>intent</code> property.
 * @enum {String}
 * @readonly
 */
RepositoryTokenRequest["IntentEnum"] = {
  /**
   * value: "read"
   * @const
   */
  read: "read",
};

export default RepositoryTokenRequest;
