/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import Repository from "../model/Repository";

declare class RepositoryListResponse {
  "repositories": Repository[];

  static constructFromObject(
    data: any,
    obj?: RepositoryListResponse,
  ): RepositoryListResponse;
  static validateJSON(data: any): boolean;
}

export default RepositoryListResponse;
