/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The RouteTransformSettings model module.
 * @module model/RouteTransformSettings
 * @version 4.0.0
 */
class RouteTransformSettings {
  /**
   * Constructs a new <code>RouteTransformSettings</code>.
   * Settings for transforming route payloads before delivery. Supports format selection and JSONata-based transformations.
   * @alias module:model/RouteTransformSettings
   */
  constructor() {
    RouteTransformSettings.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>RouteTransformSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RouteTransformSettings} obj Optional instance to populate.
   * @return {module:model/RouteTransformSettings} The populated <code>RouteTransformSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RouteTransformSettings();

      if (data.hasOwnProperty("format")) {
        obj["format"] = ApiClient.convertToType(data["format"], "String");
      }
      if (data.hasOwnProperty("jsonata")) {
        obj["jsonata"] = ApiClient.convertToType(data["jsonata"], "String");
      }
      if (data.hasOwnProperty("jsonata_in")) {
        obj["jsonata_in"] = ApiClient.convertToType(
          data["jsonata_in"],
          "String"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>RouteTransformSettings</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RouteTransformSettings</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["format"] &&
      !(typeof data["format"] === "string" || data["format"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `format` to be a primitive type in the JSON string but got " +
          data["format"]
      );
    }
    // ensure the json data is a string
    if (
      data["jsonata"] &&
      !(
        typeof data["jsonata"] === "string" || data["jsonata"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `jsonata` to be a primitive type in the JSON string but got " +
          data["jsonata"]
      );
    }
    // ensure the json data is a string
    if (
      data["jsonata_in"] &&
      !(
        typeof data["jsonata_in"] === "string" ||
        data["jsonata_in"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `jsonata_in` to be a primitive type in the JSON string but got " +
          data["jsonata_in"]
      );
    }

    return true;
  }
}

/**
 * Output format for transformed data (e.g., \"json\", \"xml\", \"text\").
 * @member {String} format
 */
RouteTransformSettings.prototype["format"] = undefined;

/**
 * JSONata expression used to transform the data payload (outgoing).
 * @member {String} jsonata
 */
RouteTransformSettings.prototype["jsonata"] = undefined;

/**
 * JSONata expression used to transform the data payload (incoming).
 * @member {String} jsonata_in
 */
RouteTransformSettings.prototype["jsonata_in"] = undefined;

export default RouteTransformSettings;
