/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import SatelliteDataUsage from "../model/SatelliteDataUsage";

declare class SatellitePlan {
  "activated": number;
  "last_session_at"?: number;
  "minimum_billable_bytes"?: number;
  "ntn_provider": string;
  "psid": string;
  "satellite_data_usage"?: SatelliteDataUsage;

  static constructFromObject(data: any, obj?: SatellitePlan): SatellitePlan;
  static validateJSON(data: any): boolean;
}

export default SatellitePlan;
