/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class SlackWebHookNotification {
  "message_type"?: "text" | "blocks";
  "text"?: string;
  "url"?: string;

  static readonly MessageTypeEnum: { text: "text"; blocks: "blocks" };

  static constructFromObject(
    data: any,
    obj?: SlackWebHookNotification,
  ): SlackWebHookNotification;
  static validateJSON(data: any): boolean;
}

export default SlackWebHookNotification;
