/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class SlackBearerNotification {
  constructor();

  "channel"?: string;
  "message_type"?: "text" | "blocks";
  "text"?: string;
  "token"?: string;

  static readonly MessageTypeEnum: { text: "text"; blocks: "blocks" };

  static constructFromObject(
    data: any,
    obj?: SlackBearerNotification,
  ): SlackBearerNotification;
  static validateJSON(data: any): boolean;
}

export default SlackBearerNotification;
