/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Filter from "./Filter";
import RouteTransformSettings from "./RouteTransformSettings";

/**
 * The ThingworxRoute model module.
 * @module model/ThingworxRoute
 * @version 6.0.0
 */
class ThingworxRoute {
  /**
   * Constructs a new <code>ThingworxRoute</code>.
   * @alias module:model/ThingworxRoute
   */
  constructor() {
    ThingworxRoute.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ThingworxRoute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ThingworxRoute} obj Optional instance to populate.
   * @return {module:model/ThingworxRoute} The populated <code>ThingworxRoute</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ThingworxRoute();

      if (data.hasOwnProperty("app_key")) {
        obj["app_key"] = ApiClient.convertToType(data["app_key"], "String");
      }
      if (data.hasOwnProperty("filter")) {
        obj["filter"] = Filter.constructFromObject(data["filter"]);
      }
      if (data.hasOwnProperty("fleets")) {
        obj["fleets"] = ApiClient.convertToType(data["fleets"], ["String"]);
      }
      if (data.hasOwnProperty("throttle_ms")) {
        obj["throttle_ms"] = ApiClient.convertToType(
          data["throttle_ms"],
          "Number"
        );
      }
      if (data.hasOwnProperty("timeout")) {
        obj["timeout"] = ApiClient.convertToType(data["timeout"], "Number");
      }
      if (data.hasOwnProperty("transform")) {
        obj["transform"] = RouteTransformSettings.constructFromObject(
          data["transform"]
        );
      }
      if (data.hasOwnProperty("url")) {
        obj["url"] = ApiClient.convertToType(data["url"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ThingworxRoute</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ThingworxRoute</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["app_key"] &&
      !(
        typeof data["app_key"] === "string" || data["app_key"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `app_key` to be a primitive type in the JSON string but got " +
          data["app_key"]
      );
    }
    // validate the optional field `filter`
    if (data["filter"]) {
      // data not null
      Filter.validateJSON(data["filter"]);
    }
    // ensure the json data is an array
    if (!Array.isArray(data["fleets"])) {
      throw new Error(
        "Expected the field `fleets` to be an array in the JSON data but got " +
          data["fleets"]
      );
    }
    // validate the optional field `transform`
    if (data["transform"]) {
      // data not null
      RouteTransformSettings.validateJSON(data["transform"]);
    }
    // ensure the json data is a string
    if (
      data["url"] &&
      !(typeof data["url"] === "string" || data["url"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `url` to be a primitive type in the JSON string but got " +
          data["url"]
      );
    }

    return true;
  }
}

/**
 * @member {String} app_key
 */
ThingworxRoute.prototype["app_key"] = undefined;

/**
 * @member {module:model/Filter} filter
 */
ThingworxRoute.prototype["filter"] = undefined;

/**
 * @member {Array.<String>} fleets
 */
ThingworxRoute.prototype["fleets"] = undefined;

/**
 * @member {Number} throttle_ms
 */
ThingworxRoute.prototype["throttle_ms"] = undefined;

/**
 * @member {Number} timeout
 */
ThingworxRoute.prototype["timeout"] = undefined;

/**
 * @member {module:model/RouteTransformSettings} transform
 */
ThingworxRoute.prototype["transform"] = undefined;

/**
 * @member {String} url
 */
ThingworxRoute.prototype["url"] = undefined;

export default ThingworxRoute;
