/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import Filter from "../model/Filter";
import RouteTransformSettings from "../model/RouteTransformSettings";

declare class ThingworxRoute {
  "app_key"?: string;
  "filter"?: Filter;
  "fleets"?: string[];
  "throttle_ms"?: number;
  "timeout"?: number;
  "transform"?: RouteTransformSettings;
  "url"?: string;

  static constructFromObject(data: any, obj?: ThingworxRoute): ThingworxRoute;
  static validateJSON(data: any): boolean;
}

export default ThingworxRoute;
