/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The UpdateProjectSecretRequest model module.
 * @module model/UpdateProjectSecretRequest
 * @version 6.4.0
 */
class UpdateProjectSecretRequest {
  /**
   * Constructs a new <code>UpdateProjectSecretRequest</code>.
   * @alias module:model/UpdateProjectSecretRequest
   * @param value {String} The new secret value (encrypted at rest, never returned).
   */
  constructor(value) {
    UpdateProjectSecretRequest.initialize(this, value);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, value) {
    obj["value"] = value;
  }

  /**
   * Constructs a <code>UpdateProjectSecretRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateProjectSecretRequest} obj Optional instance to populate.
   * @return {module:model/UpdateProjectSecretRequest} The populated <code>UpdateProjectSecretRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateProjectSecretRequest();

      if (data.hasOwnProperty("value")) {
        obj["value"] = ApiClient.convertToType(data["value"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>UpdateProjectSecretRequest</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateProjectSecretRequest</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of UpdateProjectSecretRequest.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    // ensure the json data is a string
    if (
      data["value"] &&
      !(typeof data["value"] === "string" || data["value"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `value` to be a primitive type in the JSON string but got " +
          data["value"]
      );
    }

    return true;
  }
}

UpdateProjectSecretRequest.RequiredProperties = ["value"];

/**
 * The new secret value (encrypted at rest, never returned).
 * @member {String} value
 */
UpdateProjectSecretRequest.prototype["value"] = undefined;

export default UpdateProjectSecretRequest;
