/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The UpdateHostFirmwareRequest model module.
 * @module model/UpdateHostFirmwareRequest
 * @version 6.2.0
 */
class UpdateHostFirmwareRequest {
  /**
   * Constructs a new <code>UpdateHostFirmwareRequest</code>.
   * Request body for updating host firmware metadata. All fields are optional; only provided fields will be updated.
   * @alias module:model/UpdateHostFirmwareRequest
   */
  constructor() {
    UpdateHostFirmwareRequest.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>UpdateHostFirmwareRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateHostFirmwareRequest} obj Optional instance to populate.
   * @return {module:model/UpdateHostFirmwareRequest} The populated <code>UpdateHostFirmwareRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateHostFirmwareRequest();

      if (data.hasOwnProperty("info")) {
        obj["info"] = ApiClient.convertToType(data["info"], { String: Object });
      }
      if (data.hasOwnProperty("notes")) {
        obj["notes"] = ApiClient.convertToType(data["notes"], "String");
      }
      if (data.hasOwnProperty("version")) {
        obj["version"] = ApiClient.convertToType(data["version"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>UpdateHostFirmwareRequest</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateHostFirmwareRequest</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["notes"] &&
      !(typeof data["notes"] === "string" || data["notes"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `notes` to be a primitive type in the JSON string but got " +
          data["notes"]
      );
    }
    // ensure the json data is a string
    if (
      data["version"] &&
      !(
        typeof data["version"] === "string" || data["version"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `version` to be a primitive type in the JSON string but got " +
          data["version"]
      );
    }

    return true;
  }
}

/**
 * Arbitrary JSON metadata associated with this firmware entry.
 * @member {Object.<String, Object>} info
 */
UpdateHostFirmwareRequest.prototype["info"] = undefined;

/**
 * Notes describing this firmware version.
 * @member {String} notes
 */
UpdateHostFirmwareRequest.prototype["notes"] = undefined;

/**
 * The firmware version string.
 * @member {String} version
 */
UpdateHostFirmwareRequest.prototype["version"] = undefined;

export default UpdateHostFirmwareRequest;
