/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The UsageEventsData model module.
 * @module model/UsageEventsData
 * @version 6.0.0
 */
class UsageEventsData {
  /**
   * Constructs a new <code>UsageEventsData</code>.
   * @alias module:model/UsageEventsData
   * @param period {Date}
   * @param platformEvents {Number} Total platform events. Platform events are _log, _session, _health, and _geolocate events some of which are send from the device, some generated by notehub. These events are not billed.
   * @param totalDevices {Number} Total devices represented in this count
   * @param totalEvents {Number} Total events the device sent to notehub, including associated notehub generated events
   * @param watchdogEvents {Number} Watchdog events are events generated by notehub when a watchdog timer is configured for a device to indicate is has not been online for a period of time. These events are billed but should not be used to indicate a device is active, or connected, at this time.
   */
  constructor(
    period,
    platformEvents,
    totalDevices,
    totalEvents,
    watchdogEvents
  ) {
    UsageEventsData.initialize(
      this,
      period,
      platformEvents,
      totalDevices,
      totalEvents,
      watchdogEvents
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    period,
    platformEvents,
    totalDevices,
    totalEvents,
    watchdogEvents
  ) {
    obj["period"] = period;
    obj["platform_events"] = platformEvents;
    obj["total_devices"] = totalDevices;
    obj["total_events"] = totalEvents;
    obj["watchdog_events"] = watchdogEvents;
  }

  /**
   * Constructs a <code>UsageEventsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsageEventsData} obj Optional instance to populate.
   * @return {module:model/UsageEventsData} The populated <code>UsageEventsData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsageEventsData();

      if (data.hasOwnProperty("billable_events")) {
        obj["billable_events"] = ApiClient.convertToType(
          data["billable_events"],
          "Number"
        );
      }
      if (data.hasOwnProperty("device")) {
        obj["device"] = ApiClient.convertToType(data["device"], "String");
      }
      if (data.hasOwnProperty("fleet")) {
        obj["fleet"] = ApiClient.convertToType(data["fleet"], "String");
      }
      if (data.hasOwnProperty("notefiles")) {
        obj["notefiles"] = ApiClient.convertToType(data["notefiles"], {
          String: "Number",
        });
      }
      if (data.hasOwnProperty("period")) {
        obj["period"] = ApiClient.convertToType(data["period"], "Date");
      }
      if (data.hasOwnProperty("platform_events")) {
        obj["platform_events"] = ApiClient.convertToType(
          data["platform_events"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_days_in_period")) {
        obj["total_days_in_period"] = ApiClient.convertToType(
          data["total_days_in_period"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_devices")) {
        obj["total_devices"] = ApiClient.convertToType(
          data["total_devices"],
          "Number"
        );
      }
      if (data.hasOwnProperty("total_events")) {
        obj["total_events"] = ApiClient.convertToType(
          data["total_events"],
          "Number"
        );
      }
      if (data.hasOwnProperty("watchdog_events")) {
        obj["watchdog_events"] = ApiClient.convertToType(
          data["watchdog_events"],
          "Number"
        );
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>UsageEventsData</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsageEventsData</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of UsageEventsData.RequiredProperties) {
      if (!data[property]) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data)
        );
      }
    }
    // ensure the json data is a string
    if (
      data["device"] &&
      !(typeof data["device"] === "string" || data["device"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `device` to be a primitive type in the JSON string but got " +
          data["device"]
      );
    }
    // ensure the json data is a string
    if (
      data["fleet"] &&
      !(typeof data["fleet"] === "string" || data["fleet"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `fleet` to be a primitive type in the JSON string but got " +
          data["fleet"]
      );
    }

    return true;
  }
}

UsageEventsData.RequiredProperties = [
  "period",
  "platform_events",
  "total_devices",
  "total_events",
  "watchdog_events",
];

/**
 * Events that are billable, this include all events except platform events
 * @member {Number} billable_events
 */
UsageEventsData.prototype["billable_events"] = undefined;

/**
 * @member {String} device
 */
UsageEventsData.prototype["device"] = undefined;

/**
 * @member {String} fleet
 */
UsageEventsData.prototype["fleet"] = undefined;

/**
 * Count of events per notefile. Only present when includeNotefiles=true is specified.
 * @member {Object.<String, Number>} notefiles
 */
UsageEventsData.prototype["notefiles"] = undefined;

/**
 * @member {Date} period
 */
UsageEventsData.prototype["period"] = undefined;

/**
 * Total platform events. Platform events are _log, _session, _health, and _geolocate events some of which are send from the device, some generated by notehub. These events are not billed.
 * @member {Number} platform_events
 */
UsageEventsData.prototype["platform_events"] = undefined;

/**
 * The total number of days in this period. Useful for calculating daily averages for month period. Note that the current period will be the total number of days in the current period, including days in the future.
 * @member {Number} total_days_in_period
 */
UsageEventsData.prototype["total_days_in_period"] = undefined;

/**
 * Total devices represented in this count
 * @member {Number} total_devices
 */
UsageEventsData.prototype["total_devices"] = undefined;

/**
 * Total events the device sent to notehub, including associated notehub generated events
 * @member {Number} total_events
 */
UsageEventsData.prototype["total_events"] = undefined;

/**
 * Watchdog events are events generated by notehub when a watchdog timer is configured for a device to indicate is has not been online for a period of time. These events are billed but should not be used to indicate a device is active, or connected, at this time.
 * @member {Number} watchdog_events
 */
UsageEventsData.prototype["watchdog_events"] = undefined;

export default UsageEventsData;
