/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

declare class UsageRouteLogsData {
  "avg_latency_ms"?: number;
  "failed_routes": number;
  "period": Date;
  "route"?: string;
  "successful_routes": number;
  "total_routes": number;

  static constructFromObject(
    data: any,
    obj?: UsageRouteLogsData,
  ): UsageRouteLogsData;
  static validateJSON(data: any): boolean;
}

export default UsageRouteLogsData;
