/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class UsageData {
  constructor(period: Date, totalBytes: number);

  "billable_bytes_total"?: number;
  "downlink_bytes"?: number;
  "downlink_bytes_billable"?: number;
  "downlink_packets"?: number;
  "period": Date;
  "total_bytes": number;
  "uplink_bytes"?: number;
  "uplink_bytes_billable"?: number;
  "uplink_packets"?: number;

  static constructFromObject(data: any, obj?: UsageData): UsageData;
  static validateJSON(data: any): boolean;
}

export default UsageData;
