/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by OpenAPI Generator from the model templates.
 * Do not edit it manually.
 */

declare class UsageEventsData {
  constructor(
    period: Date,
    platformEvents: number,
    totalDevices: number,
    totalEvents: number,
    watchdogEvents: number,
  );

  "billable_events"?: number;
  "device"?: string;
  "fleet"?: string;
  "notefiles"?: { [key: string]: number };
  "period": Date;
  "platform_events": number;
  "total_days_in_period"?: number;
  "total_devices": number;
  "total_events": number;
  "total_fw_updates"?: number;
  "total_reboots"?: number;
  "watchdog_events": number;

  static constructFromObject(data: any, obj?: UsageEventsData): UsageEventsData;
  static validateJSON(data: any): boolean;
}

export default UsageEventsData;
