/**
 * Notehub API
 * The OpenAPI definition for the Notehub.io API.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: engineering@blues.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The WebhookSettings model module.
 * @module model/WebhookSettings
 * @version 2.1.0
 */
class WebhookSettings {
  /**
   * Constructs a new <code>WebhookSettings</code>.
   * @alias module:model/WebhookSettings
   */
  constructor() {
    WebhookSettings.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>WebhookSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookSettings} obj Optional instance to populate.
   * @return {module:model/WebhookSettings} The populated <code>WebhookSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookSettings();

      if (data.hasOwnProperty("disabled")) {
        obj["disabled"] = ApiClient.convertToType(data["disabled"], "Boolean");
      }
      if (data.hasOwnProperty("id")) {
        obj["id"] = ApiClient.convertToType(data["id"], "String");
      }
      if (data.hasOwnProperty("transform")) {
        obj["transform"] = ApiClient.convertToType(data["transform"], "String");
      }
    } else if (data === null) {
      return null;
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>WebhookSettings</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookSettings</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data["id"] &&
      !(typeof data["id"] === "string" || data["id"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `id` to be a primitive type in the JSON string but got " +
          data["id"]
      );
    }
    // ensure the json data is a string
    if (
      data["transform"] &&
      !(
        typeof data["transform"] === "string" ||
        data["transform"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `transform` to be a primitive type in the JSON string but got " +
          data["transform"]
      );
    }

    return true;
  }
}

/**
 * Flag indicating if the webhook is disabled
 * @member {Boolean} disabled
 */
WebhookSettings.prototype["disabled"] = undefined;

/**
 * Webhook ID
 * @member {String} id
 */
WebhookSettings.prototype["id"] = undefined;

/**
 * Transformation to be applied to the event
 * @member {String} transform
 */
WebhookSettings.prototype["transform"] = undefined;

export default WebhookSettings;
