/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import ApiClient from "../ApiClient";
import NotehubRoute from "../model/NotehubRoute";
import NotehubRouteSummary from "../model/NotehubRouteSummary";
import RouteLog from "../model/RouteLog";

declare class RouteApi {
  constructor(apiClient?: ApiClient);

  createRouteWithHttpInfo(
    projectOrProductUID: string,
    notehubRoute: NotehubRoute,
  ): Promise<{ data: NotehubRoute; response: unknown }>;

  createRoute(
    projectOrProductUID: string,
    notehubRoute: NotehubRoute,
  ): Promise<NotehubRoute>;

  deleteRouteWithHttpInfo(
    projectOrProductUID: string,
    routeUID: string,
  ): Promise<{ data: void; response: unknown }>;

  deleteRoute(projectOrProductUID: string, routeUID: string): Promise<void>;

  getRouteWithHttpInfo(
    projectOrProductUID: string,
    routeUID: string,
  ): Promise<{ data: NotehubRoute; response: unknown }>;

  getRoute(
    projectOrProductUID: string,
    routeUID: string,
  ): Promise<NotehubRoute>;

  getRouteLogsByRouteWithHttpInfo(
    projectOrProductUID: string,
    routeUID: string,
    opts?: {
      pageSize?: number;
      pageNum?: number;
      deviceUID?: string[];
      sortBy?: string;
      sortOrder?: string;
      startDate?: number;
      endDate?: number;
      systemFilesOnly?: boolean;
      mostRecentOnly?: boolean;
      files?: string;
      routingStatus?: string[];
      responseStatus?: string[];
    },
  ): Promise<{ data: RouteLog[]; response: unknown }>;

  getRouteLogsByRoute(
    projectOrProductUID: string,
    routeUID: string,
    opts?: {
      pageSize?: number;
      pageNum?: number;
      deviceUID?: string[];
      sortBy?: string;
      sortOrder?: string;
      startDate?: number;
      endDate?: number;
      systemFilesOnly?: boolean;
      mostRecentOnly?: boolean;
      files?: string;
      routingStatus?: string[];
      responseStatus?: string[];
    },
  ): Promise<RouteLog[]>;

  getRoutesWithHttpInfo(
    projectOrProductUID: string,
  ): Promise<{ data: NotehubRouteSummary[]; response: unknown }>;

  getRoutes(projectOrProductUID: string): Promise<NotehubRouteSummary[]>;

  updateRouteWithHttpInfo(
    projectOrProductUID: string,
    routeUID: string,
    notehubRoute: NotehubRoute,
  ): Promise<{ data: NotehubRoute; response: unknown }>;

  updateRoute(
    projectOrProductUID: string,
    routeUID: string,
    notehubRoute: NotehubRoute,
  ): Promise<NotehubRoute>;
}

export default RouteApi;
