/**
 * Notehub API - TypeScript definitions
 *
 * NOTE: This file is auto-generated by .github/scripts/generate-types.js from the
 * generated JavaScript sources. Do not edit it manually.
 */

import ApiClient from "../ApiClient";
import GetWebhooks200Response from "../model/GetWebhooks200Response";
import WebhookSettings from "../model/WebhookSettings";

declare class WebhookApi {
  constructor(apiClient?: ApiClient);

  createLegacyWebhookEventWithHttpInfo(
    productUID: string,
    deviceUID: string,
    requestBody: any,
  ): Promise<{ data: void; response: unknown }>;

  createLegacyWebhookEvent(
    productUID: string,
    deviceUID: string,
    requestBody: any,
  ): Promise<void>;

  createWebhookWithHttpInfo(
    projectOrProductUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<{ data: void; response: unknown }>;

  createWebhook(
    projectOrProductUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<void>;

  createWebhookDeviceEventByProductWithHttpInfo(
    productUID: string,
    webhookUID: string,
    deviceUID: string,
    requestBody: any,
  ): Promise<{ data: void; response: unknown }>;

  createWebhookDeviceEventByProduct(
    productUID: string,
    webhookUID: string,
    deviceUID: string,
    requestBody: any,
  ): Promise<void>;

  createWebhookEventByProductWithHttpInfo(
    productUID: string,
    webhookUID: string,
    requestBody: any,
  ): Promise<{ data: void; response: unknown }>;

  createWebhookEventByProduct(
    productUID: string,
    webhookUID: string,
    requestBody: any,
  ): Promise<void>;

  deleteWebhookWithHttpInfo(
    projectOrProductUID: string,
    webhookUID: string,
  ): Promise<{ data: void; response: unknown }>;

  deleteWebhook(projectOrProductUID: string, webhookUID: string): Promise<void>;

  getWebhookWithHttpInfo(
    projectOrProductUID: string,
    webhookUID: string,
  ): Promise<{ data: WebhookSettings; response: unknown }>;

  getWebhook(
    projectOrProductUID: string,
    webhookUID: string,
  ): Promise<WebhookSettings>;

  getWebhookSettingsByProductWithHttpInfo(
    productUID: string,
    webhookUID: string,
  ): Promise<{ data: WebhookSettings; response: unknown }>;

  getWebhookSettingsByProduct(
    productUID: string,
    webhookUID: string,
  ): Promise<WebhookSettings>;

  getWebhooksWithHttpInfo(
    projectOrProductUID: string,
  ): Promise<{ data: GetWebhooks200Response; response: unknown }>;

  getWebhooks(projectOrProductUID: string): Promise<GetWebhooks200Response>;

  updateLegacyWebhookSessionWithHttpInfo(
    productUID: string,
    deviceUID: string,
    opts?: {},
  ): Promise<{ data: void; response: unknown }>;

  updateLegacyWebhookSession(
    productUID: string,
    deviceUID: string,
    opts?: {},
  ): Promise<void>;

  updateWebhookWithHttpInfo(
    projectOrProductUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<{ data: void; response: unknown }>;

  updateWebhook(
    projectOrProductUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<void>;

  updateWebhookSettingsByProductWithHttpInfo(
    productUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<{ data: void; response: unknown }>;

  updateWebhookSettingsByProduct(
    productUID: string,
    webhookUID: string,
    webhookSettings: WebhookSettings,
  ): Promise<void>;
}

export default WebhookApi;
