name: Automatically create new pull request

on: push

jobs:
  create_update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: update notehub openapi.yaml file
          title: Update Notehub-js OpenAPI.yaml file
          branch: feat-automate-pr-creation
          assignees: paigen11

