name: Publish beta version of notehub-js to npm

on:
  push:
    branches:
      - "test-release-*"
    paths:
      - "openapi.yaml"

jobs:
  publish-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version from config.json
        id: get_version
        run: |
          CURRENT_VERSION=$(jq -r .projectVersion config.json)
          echo "Current project version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment Beta Version
        id: update_version
        run: |
          # Check if the current version already has a beta suffix
          if [[ "$CURRENT_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-beta\.([0-9]+))?$ ]]; then
            # Extract major, minor, patch, and the current beta version number
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            CURRENT_BETA="${BASH_REMATCH[5]:-0}"  # Use 0 if no beta suffix is present

            # Increment the beta version by 1
            NEW_BETA=$((CURRENT_BETA + 1))
            
            # Construct the new version with the incremented beta suffix
            NEW_VERSION="$MAJOR.$MINOR.$PATCH-beta.$NEW_BETA"
          else
            echo "Error: Current version format is not compatible. Please ensure it follows the semantic versioning format."
            exit 1
          fi

          # Update config.json with the new version
          jq --arg new_version "$NEW_VERSION" '.projectVersion = $new_version' config.json > config.tmp.json && mv config.tmp.json config.json

          echo "Updated project version to: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Remove Outdated SDK Folder
        run: rm -rf src

      - name: Generate New SDK
        run: npm run generateDocs

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish Beta Version to npm
        run: |
          echo "Publishing beta version to npm... $NEW_VERSION"
          # cd src
          # npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit Updated config.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add config.json
          git commit -m "Update project version to ${{ steps.update_version.outputs.new_version }} [skip ci]"
          git push
