name: Publish beta version of notehub-js to npm

on:
  push:
    branches:
      - "test-release-*"
    paths:
      - "openapi.yaml"

jobs:
  publish-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version from config.json
        id: get_version
        run: |
          CURRENT_VERSION=$(jq -r .projectVersion config.json)
          echo "Current project version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Get existing beta versions from npm
        id: get_existing_versions
        run: |
          # Query npm for existing versions of the package
          EXISTING_VERSIONS=$(npm show @blues-inc/notehub-js versions --json)
          echo "Existing versions on npm: $EXISTING_VERSIONS"

          # Extract only beta versions for the current major.minor.patch version
          CURRENT_BETA_VERSIONS=$(echo "$EXISTING_VERSIONS" | jq -r '.[]' | grep -E "^${CURRENT_VERSION}-beta\.[0-9]+$" || true)
          echo "Current beta versions: $CURRENT_BETA_VERSIONS"

          if [ -z "$CURRENT_BETA_VERSIONS" ]; then
            # If no beta versions exist, set the initial beta version number
            NEXT_BETA_VERSION=1
          else
            # Get the highest beta version number and increment it
            HIGHEST_BETA_VERSION=$(echo "$CURRENT_BETA_VERSIONS" | grep -oE 'beta\.[0-9]+' | sort -V | tail -n 1 | grep -oE '[0-9]+')
            NEXT_BETA_VERSION=$((HIGHEST_BETA_VERSION + 1))
          fi
          echo "Next beta version: $NEXT_BETA_VERSION"

          # Use the branch name to create a unique version suffix
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          UNIQUE_VERSION="${CURRENT_VERSION}-beta.${NEXT_BETA_VERSION}-${BRANCH_NAME}"

          echo "Updated version will be: $UNIQUE_VERSION"
          echo "NEW_VERSION=$UNIQUE_VERSION" >> $GITHUB_ENV
      - name: Update version to beta
        run: |
          # Update config.json with the new beta version
          jq --arg new_version "$NEW_VERSION" '.projectVersion = $NEW_VERSION' config.json > config.tmp.json && mv config.tmp.json config.json

          echo "Updated project version to: $NEW_VERSION"

      - name: Install Dependencies
        run: npm install

      - name: Remove Outdated SDK Folder
        run: rm -rf src

      - name: Generate New SDK
        run: npm run generateDocs

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd src
          npm install

      - name: Publish Beta Version to npm
        run: |
          echo "Publishing beta version to npm... $NEW_VERSION"
          # cd src
          # npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit Updated config.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add config.json
          git commit -m "Update project version to ${{ steps.update_version.outputs.new_version }} [skip ci]"
          git push
