name: Publish notehub-js to npm

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Use Node.js 16 
        uses: actions/setup-node@v3
        working-directory: ./src
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./src
        run: npm ci --ignore-scripts

      - name: Publish to npm
        run: npm publish
        working-directory: ./src
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
