name: Publish production to npm

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: sudo npm install -g npm@latest

      - name: Verify npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --provenance --access public
