name: Publish production to npm

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./src
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v7
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: npm install -g npm@11

      - name: Verify npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --provenance --access public
