name: Publish notehub-js to npm

on: 
  release:
    types: [created]

jobs:
  npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate release changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci 

      - name: Publish to npm  
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
