name: Publish beta version of notehub-js to npm

on:
  push:
    branches:
      - "test-release-**"
    paths:
      - "openapi.yaml"

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to push version updates

jobs:
  publish-beta:
    uses: ./.github/workflows/publish-npm-reusable.yml
    with:
      is_beta: true
    permissions:
      id-token: write
      contents: write
